# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'single_asset_analyse_tab3_H.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDateEdit,
    QDoubleSpinBox, QGroupBox, QHBoxLayout, QHeaderView,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QSpacerItem, QTableView, QTableWidget, QTableWidgetItem,
    QVBoxLayout, QWidget)

from pyqtgraph import PlotWidget

class Ui_SingleAssetAnalyseTab(object):
    def setupUi(self, SingleAssetAnalyseTab):
        if not SingleAssetAnalyseTab.objectName():
            SingleAssetAnalyseTab.setObjectName(u"SingleAssetAnalyseTab")
        SingleAssetAnalyseTab.resize(1981, 4026)
        self.verticalLayout_2 = QVBoxLayout(SingleAssetAnalyseTab)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.widget = QWidget(SingleAssetAnalyseTab)
        self.widget.setObjectName(u"widget")
        self.widget.setMinimumSize(QSize(1000, 1000))
        self.priceAantalChart = PlotWidget(self.widget)
        self.priceAantalChart.setObjectName(u"priceAantalChart")
        self.priceAantalChart.setGeometry(QRect(10, 830, 811, 191))
        self.verticalLayout_7 = QVBoxLayout(self.priceAantalChart)
        self.verticalLayout_7.setSpacing(9)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(9, 9, 9, 9)
        self.verticalLayoutWidget_4 = QWidget(self.widget)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(10, 380, 811, 431))
        self.layoutChart = QVBoxLayout(self.verticalLayoutWidget_4)
        self.layoutChart.setSpacing(2)
        self.layoutChart.setObjectName(u"layoutChart")
        self.layoutChart.setContentsMargins(2, 2, 2, 2)
        self.resultaatChart = PlotWidget(self.widget)
        self.resultaatChart.setObjectName(u"resultaatChart")
        self.resultaatChart.setGeometry(QRect(10, 1030, 811, 191))
        self.verticalLayout_9 = QVBoxLayout(self.resultaatChart)
        self.verticalLayout_9.setSpacing(9)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayoutWidget = QWidget(self.widget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 10, 801, 31))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.stepSizeBox = QDoubleSpinBox(self.horizontalLayoutWidget)
        self.stepSizeBox.setObjectName(u"stepSizeBox")
        self.stepSizeBox.setMaximumSize(QSize(80, 16777215))
        self.stepSizeBox.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        self.stepSizeBox.setDecimals(6)
        self.stepSizeBox.setValue(0.020000000000000)

        self.horizontalLayout.addWidget(self.stepSizeBox, 0, Qt.AlignmentFlag.AlignLeft)

        self.startDate = QDateEdit(self.horizontalLayoutWidget)
        self.startDate.setObjectName(u"startDate")
        self.startDate.setMaximumSize(QSize(120, 16777215))
        self.startDate.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        self.startDate.setCalendarPopup(True)

        self.horizontalLayout.addWidget(self.startDate, 0, Qt.AlignmentFlag.AlignLeft)

        self.endDate = QDateEdit(self.horizontalLayoutWidget)
        self.endDate.setObjectName(u"endDate")
        self.endDate.setMaximumSize(QSize(120, 16777215))
        self.endDate.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        self.endDate.setCalendarPopup(True)

        self.horizontalLayout.addWidget(self.endDate, 0, Qt.AlignmentFlag.AlignLeft)

        self.comboBoxStatus = QComboBox(self.horizontalLayoutWidget)
        self.comboBoxStatus.setObjectName(u"comboBoxStatus")
        self.comboBoxStatus.setMaximumSize(QSize(80, 16777215))
        self.comboBoxStatus.setStyleSheet(u"background-color: rgb(230, 230, 230);")

        self.horizontalLayout.addWidget(self.comboBoxStatus)

        self.comboBoxValueGrow = QComboBox(self.horizontalLayoutWidget)
        self.comboBoxValueGrow.setObjectName(u"comboBoxValueGrow")
        self.comboBoxValueGrow.setMaximumSize(QSize(80, 16777215))
        self.comboBoxValueGrow.setStyleSheet(u"background-color: rgb(230, 230, 230);")

        self.horizontalLayout.addWidget(self.comboBoxValueGrow)

        self.comboBoxSector = QComboBox(self.horizontalLayoutWidget)
        self.comboBoxSector.setObjectName(u"comboBoxSector")
        self.comboBoxSector.setMaximumSize(QSize(140, 16777215))
        self.comboBoxSector.setStyleSheet(u"background-color: rgb(230, 230, 230);")

        self.horizontalLayout.addWidget(self.comboBoxSector)

        self.comboBoxRegio = QComboBox(self.horizontalLayoutWidget)
        self.comboBoxRegio.setObjectName(u"comboBoxRegio")
        self.comboBoxRegio.setMaximumSize(QSize(60, 16777215))
        self.comboBoxRegio.setStyleSheet(u"background-color: rgb(230, 230, 230);")

        self.horizontalLayout.addWidget(self.comboBoxRegio)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.horizontalLayoutWidget_2 = QWidget(self.widget)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(840, 10, 551, 31))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.lineEditFilterOptiesOpen = QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditFilterOptiesOpen.setObjectName(u"lineEditFilterOptiesOpen")
        self.lineEditFilterOptiesOpen.setMinimumSize(QSize(300, 24))
        self.lineEditFilterOptiesOpen.setMaximumSize(QSize(450, 16777215))
        self.lineEditFilterOptiesOpen.setStyleSheet(u"background-color: rgb(230, 230, 230);")

        self.horizontalLayout_2.addWidget(self.lineEditFilterOptiesOpen)

        self.buttonClearFiltersOptiesOpen = QPushButton(self.horizontalLayoutWidget_2)
        self.buttonClearFiltersOptiesOpen.setObjectName(u"buttonClearFiltersOptiesOpen")
        self.buttonClearFiltersOptiesOpen.setMaximumSize(QSize(150, 16777215))
        self.buttonClearFiltersOptiesOpen.setStyleSheet(u"background-color: rgb(230, 230, 230);")

        self.horizontalLayout_2.addWidget(self.buttonClearFiltersOptiesOpen, 0, Qt.AlignmentFlag.AlignRight)

        self.payoff_table = QTableWidget(self.widget)
        self.payoff_table.setObjectName(u"payoff_table")
        self.payoff_table.setGeometry(QRect(6, 46, 811, 257))
        self.payoff_table.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.payoff_table.verticalHeader().setMinimumSectionSize(30)
        self.tableViewOptiesOpen = QTableView(self.widget)
        self.tableViewOptiesOpen.setObjectName(u"tableViewOptiesOpen")
        self.tableViewOptiesOpen.setGeometry(QRect(840, 46, 1081, 257))
        self.tableViewOptiesOpen.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.testOrdersTable = QTableWidget(self.widget)
        self.testOrdersTable.setObjectName(u"testOrdersTable")
        self.testOrdersTable.setGeometry(QRect(840, 380, 1081, 281))
        self.tableViewOptiesOpenPut = QTableView(self.widget)
        self.tableViewOptiesOpenPut.setObjectName(u"tableViewOptiesOpenPut")
        self.tableViewOptiesOpenPut.setGeometry(QRect(840, 990, 1081, 121))
        self.tableViewOptiesOpenPut.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.tableViewOptiesOpenCall = QTableView(self.widget)
        self.tableViewOptiesOpenCall.setObjectName(u"tableViewOptiesOpenCall")
        self.tableViewOptiesOpenCall.setGeometry(QRect(840, 850, 1081, 117))
        self.tableViewOptiesOpenCall.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.tableViewAandelen = QTableView(self.widget)
        self.tableViewAandelen.setObjectName(u"tableViewAandelen")
        self.tableViewAandelen.setGeometry(QRect(840, 1140, 431, 77))
        self.tableViewAandelen.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.tableViewSprinters = QTableView(self.widget)
        self.tableViewSprinters.setObjectName(u"tableViewSprinters")
        self.tableViewSprinters.setGeometry(QRect(1290, 1140, 631, 78))
        self.tableViewSprinters.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.groupBox = QGroupBox(self.widget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 310, 811, 61))
        self.lblPctLineair = QLabel(self.groupBox)
        self.lblPctLineair.setObjectName(u"lblPctLineair")
        self.lblPctLineair.setGeometry(QRect(650, 31, 70, 16))
        self.lblPctLineair.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(180, 10, 70, 20))
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(360, 10, 70, 16))
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lblPctChange = QLabel(self.groupBox)
        self.lblPctChange.setObjectName(u"lblPctChange")
        self.lblPctChange.setGeometry(QRect(180, 30, 70, 16))
        self.lblPctChange.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lblKoers = QLabel(self.groupBox)
        self.lblKoers.setObjectName(u"lblKoers")
        self.lblKoers.setGeometry(QRect(360, 30, 70, 16))
        self.lblKoers.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(270, 10, 70, 16))
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbKoersPrev = QLabel(self.groupBox)
        self.lbKoersPrev.setObjectName(u"lbKoersPrev")
        self.lbKoersPrev.setGeometry(QRect(270, 30, 70, 16))
        self.lbKoersPrev.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(650, 11, 70, 16))
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lblPctDelta = QLabel(self.groupBox)
        self.lblPctDelta.setObjectName(u"lblPctDelta")
        self.lblPctDelta.setGeometry(QRect(730, 31, 70, 16))
        self.lblPctDelta.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(730, 11, 70, 16))
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(450, 10, 70, 20))
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lblNetChange = QLabel(self.groupBox)
        self.lblNetChange.setObjectName(u"lblNetChange")
        self.lblNetChange.setGeometry(QRect(450, 30, 70, 16))
        self.lblNetChange.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.asset_selector = QComboBox(self.groupBox)
        self.asset_selector.setObjectName(u"asset_selector")
        self.asset_selector.setGeometry(QRect(10, 13, 131, 35))
        self.asset_selector.setMaximumSize(QSize(150, 16777215))
        self.asset_selector.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        self.groupBox_2 = QGroupBox(self.widget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(840, 310, 1081, 61))
        self.buttonDeleteTestOrder = QPushButton(self.groupBox_2)
        self.buttonDeleteTestOrder.setObjectName(u"buttonDeleteTestOrder")
        self.buttonDeleteTestOrder.setGeometry(QRect(450, 14, 121, 31))
        self.checkBoxEnableTestOrders = QCheckBox(self.groupBox_2)
        self.checkBoxEnableTestOrders.setObjectName(u"checkBoxEnableTestOrders")
        self.checkBoxEnableTestOrders.setGeometry(QRect(22, 20, 121, 20))
        self.buttonAddTestOrder = QPushButton(self.groupBox_2)
        self.buttonAddTestOrder.setObjectName(u"buttonAddTestOrder")
        self.buttonAddTestOrder.setGeometry(QRect(320, 14, 121, 31))
        self.checkBoxAssetOrdersOnly = QCheckBox(self.groupBox_2)
        self.checkBoxAssetOrdersOnly.setObjectName(u"checkBoxAssetOrdersOnly")
        self.checkBoxAssetOrdersOnly.setGeometry(QRect(162, 20, 151, 20))
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(850, 830, 49, 16))
        self.label_3 = QLabel(self.widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(850, 970, 49, 16))
        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(850, 1120, 101, 16))
        self.label_12 = QLabel(self.widget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(1300, 1120, 101, 16))

        self.verticalLayout_2.addWidget(self.widget)

        QWidget.setTabOrder(self.asset_selector, self.stepSizeBox)
        QWidget.setTabOrder(self.stepSizeBox, self.startDate)
        QWidget.setTabOrder(self.startDate, self.endDate)
        QWidget.setTabOrder(self.endDate, self.comboBoxStatus)
        QWidget.setTabOrder(self.comboBoxStatus, self.comboBoxValueGrow)
        QWidget.setTabOrder(self.comboBoxValueGrow, self.comboBoxSector)
        QWidget.setTabOrder(self.comboBoxSector, self.comboBoxRegio)
        QWidget.setTabOrder(self.comboBoxRegio, self.lineEditFilterOptiesOpen)
        QWidget.setTabOrder(self.lineEditFilterOptiesOpen, self.buttonClearFiltersOptiesOpen)
        QWidget.setTabOrder(self.buttonClearFiltersOptiesOpen, self.checkBoxEnableTestOrders)
        QWidget.setTabOrder(self.checkBoxEnableTestOrders, self.checkBoxAssetOrdersOnly)
        QWidget.setTabOrder(self.checkBoxAssetOrdersOnly, self.buttonAddTestOrder)
        QWidget.setTabOrder(self.buttonAddTestOrder, self.buttonDeleteTestOrder)
        QWidget.setTabOrder(self.buttonDeleteTestOrder, self.testOrdersTable)

        self.retranslateUi(SingleAssetAnalyseTab)

        QMetaObject.connectSlotsByName(SingleAssetAnalyseTab)
    # setupUi

    def retranslateUi(self, SingleAssetAnalyseTab):
        SingleAssetAnalyseTab.setWindowTitle(QCoreApplication.translate("SingleAssetAnalyseTab", u"Form", None))
        self.buttonClearFiltersOptiesOpen.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Clear Filter", None))
        self.groupBox.setTitle("")
        self.lblPctLineair.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"lblPctLineair", None))
        self.label_7.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Pct. Change", None))
        self.label_6.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Koers", None))
        self.lblPctChange.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"lblPctChange", None))
        self.lblKoers.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"lblKoers", None))
        self.label_5.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Koers Prev.", None))
        self.lbKoersPrev.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"lbKoersPrev", None))
        self.label_9.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Pct Lineair", None))
        self.lblPctDelta.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"lblPctDelta", None))
        self.label_10.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Pct Delta", None))
        self.label_8.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Net. Change", None))
        self.lblNetChange.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"lblNetChange", None))
        self.groupBox_2.setTitle("")
        self.buttonDeleteTestOrder.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Delete test order", None))
        self.checkBoxEnableTestOrders.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Enable Test Orders", None))
        self.buttonAddTestOrder.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Add test order", None))
        self.checkBoxAssetOrdersOnly.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Show asset orders only", None))
        self.label_2.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Calls", None))
        self.label_3.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Puts", None))
        self.label_4.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Aandelen", None))
        self.label_12.setText(QCoreApplication.translate("SingleAssetAnalyseTab", u"Sprinters", None))
    # retranslateUi

